[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan view:cache"
]

[start]
cmd = "mkdir -p /app/storage/app/public/avatars /app/storage/app/public/blog/covers /app/storage/app/public/blog/images /app/storage/app/public/chat/images /app/storage/app/public/chat/videos && php artisan storage:link --force && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
